# Generated by Django 3.2.8 on 2021-11-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20211122_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='opentime',
            new_name='openTime',
        ),
    ]
